chore: Increase Node heap size limit
We're seeing a problem where the CI environment is failing due to memory
exhaustion:

```
ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa25510 node::Abort() [node]
 2: 0x9664d3 node::FatalError(char const*, char const*) [node]
 3: 0xb9a8be v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb9ac37 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool)
```

The Docker container has a memory limit of 16 GB, so 12 GB for Node
should be plenty.